Update LOOT-FAQs.html
loot/loot.github.io pull request #84
Opened 2021-05-18 20:54 UTC by pStyl3

Differentiate between `URL` and `File Path`.

2021-05-24 18:36 UTC, pStyl3 commented
If there aren't any objections to this, I'd like to merge this change tomorrow.

2021-05-25 05:41 UTC, sibir-ine commented on docs/help/LOOT-FAQs.html
> +    <p>If LOOT still can't update its masterlist, you can update manually by downloading <a href="https://raw.githubusercontent.com/loot/skyrim/v0.15/masterlist.yaml">this file</a> and placing it in
```suggestion
    <p>If LOOT still can't update its masterlist, you can update manually by downloading <a href="https://raw.githubusercontent.com/loot/skyrim/v0.15/masterlist.yaml">this file</a> and placing it in the <code>%LOCALAPPDATA%\LOOT\Skyrim</code> folder. Depending on your game, replace <code>skyrim</code> within the URL with <code>morrowind</code>, <code>oblivion</code>, <code>skyrimse</code>, <code>fallout3</code>, <code>falloutnv</code>, <code>fallout4</code> or <code>enderal</code> as necessary, and <code>Skyrim</code> within the folder path with <code>Morrowind</code>, <code>Oblivion</code>, <code>Skyrim Special Edition</code>, <code>Skyrim VR</code>, <code>Fallout3</code>, <code>FalloutNV</code>, <code>Fallout4</code>, <code>Fallout4VR</code>, <code>Nehrim</code>, <code>Enderal</code> or <code>Enderal Special Edition</code>.</p>
```

2021-05-25 19:39 UTC, Ortham requested changes
Sorry for the delay, I'm fine with this if sibir's suggested change is incorporated.

2021-05-25 20:09 UTC, pStyl3 commented
Done, thanks for the feedback.

2021-05-25 20:21 UTC, merged